version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sportkeeper
      POSTGRES_PASSWORD: sportkeeper
      POSTGRES_DB: sportkeeper
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    depends_on: [db]
    ports: ["8081:8080"]

  backend:
    build: .
    depends_on: [db]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8080:8080"]

volumes:
  db_data:
