version: "3.9"

services:
  # Opcional: Adminer, puede conectarse a Neon (host externo)
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"           # http://localhost:8081

  backend:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-royal-grass-ag32b4j0-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_mZghrjIa2d7k
      SPRING_JPA_HIBERNATE_DDL_AUTO: update   # en prod serio: validate + migraciones
      SPRING_SQL_INIT_MODE: never
      TZ: Europe/Madrid
    ports:
      - "8080:8080"
