version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env     # mejor no poner credenciales en claro
    #environment:
    #SPRING_PROFILES_ACTIVE: docker   para que cargue application-docker.yml (opcional)
    restart: unless-stopped
