# src/main/resources/application.yml
spring:
  application:
    name: sportkeeper
  profiles:
    default: dev
server:
  port: 8080
---
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sportkeeper}
    username: ${SPRING_DATASOURCE_USERNAME:sportkeeper}
    password: ${SPRING_DATASOURCE_PASSWORD:sportkeeper}
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:h2:mem:sportkeeper;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: never        # Cambia a 'always' si quieres ejecutar schema.sql/data.sql
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

security:
  jwt:
    secret: changemechangemechangemechangeme
